We can pass callback function to onSuccess and onError property of 3rd param of useQuery
hook to fire actions when the api fails or succeds.

```
  const onSuccess = () => {
    console.log("Perform side effect after data fetching.");
  };

  const onError = () => {
    console.log("Perform side effect after encountering error.");
  };

  const results = useQuery(
    "super-heroes",
    () => {
      return axios.get("http://localhost:4000/superheroes");
    },
    {
      onSuccess: onSuccess,
      onError: onError,
    }
  );

```

React query makes 3 api calls before calling the onError callback
Also onSuccess gets data as the parameter and onError gets error as the parameter.

```
  const onSuccess = (data) => {
    console.log("Perform side effect after data fetching.");
  };

  const onError = (error) => {
    console.log("Perform side effect after encountering error.");
  };

  const results = useQuery(
    "super-heroes",
    () => {
      return axios.get("http://localhost:4000/superheroes");
    },
    {
      onSuccess: onSuccess,
      onError: onError,
    }
  );

```
